### ISSUE TITLE
kitchen-docker support?

### ISSUE THREAD

**Issue by jmccann** [chef/kitchen-inspec#35] opened 2016-01-20 01:21 UTC
I tried using this doing kitchen testing with docker utilizing the kitchen-docker gem and it doesn't seem to run the verify tests.  I thought it'd work since it looks like kitchen-docker uses the SSH transport but it seems something more may be needed?

docker output:
```
$ kitchen list
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialized constant HTTPClient::CookieManager
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of CookieManager was here
Instance           Driver  Provisioner  Verifier  Transport  Last Action
default-centos-66  Docker  ChefZero     Inspec    Ssh        Verified
$ kitchen verify
-----> Starting Kitchen (v1.4.2)
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialized constant HTTPClient::CookieManager
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of CookieManager was here
-----> Verifying <default-centos-66>...
$$$$$$ Running legacy verify for 'Docker' Driver
       Preparing files for transfer
       Transferring files to <default-centos-66>
       Finished verifying <default-centos-66> (0m0.00s).
-----> Kitchen is finished. (0m0.95s)
$ ls test/integration/default/
node_prepare_spec.rb
```

vagrant/vbox output:
```
$ kitchen list
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialized constant HTTPClient::CookieManager
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of CookieManager was here
Instance       Driver   Provisioner  Verifier  Transport  Last Action
default-rhel6  Vagrant  ChefZero     Inspec    Ssh        Verified
$ kitchen verify
-----> Starting Kitchen (v1.4.2)
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialized constant HTTPClient::CookieManager
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of CookieManager was here
-----> Verifying <default-rhel6>...
FFFFF

Failures:

  1) System Package pcs should be installed
     Failure/Error: it { should be_installed }
       expected that `System Package pcs` is installed
     # ./test/integration/default/node_prepare_spec.rb:2:in `block (2 levels) in load'

  2) Service pcsd should be enabled
     Failure/Error: it { should be_enabled }
       expected that `Service pcsd` is enabled
     # ./test/integration/default/node_prepare_spec.rb:6:in `block (2 levels) in load'

  3) Service pcsd should be running
     Failure/Error: it { should be_running }
       expected that `Service pcsd` is running
     # ./test/integration/default/node_prepare_spec.rb:7:in `block (2 levels) in load'

  4) Service pacemaker should be running
     Failure/Error: it { should be_running }
       expected that `Service pacemaker` is running
     # ./test/integration/default/node_prepare_spec.rb:11:in `block (2 levels) in load'

  5) Service corosync should be running
     Failure/Error: it { should be_running }
       expected that `Service corosync` is running
     # ./test/integration/default/node_prepare_spec.rb:17:in `block (2 levels) in load'

Finished in 0.75939 seconds (files took 0.37673 seconds to load)
5 examples, 5 failures

Failed examples:

rspec  # System Package pcs should be installed
rspec  # Service pcsd should be enabled
rspec  # Service pcsd should be running
rspec  # Service pacemaker should be running
rspec  # Service corosync should be running

       Finished verifying <default-rhel6> (0m1.01s).
-----> Kitchen is finished. (0m2.10s)
zlib(finalizer): the stream was freed prematurely.
$ ls test/integration/default/
node_prepare_spec.rb
```

Thanks!

**Comment by chris-rock** [comment] 2016-01-20 11:28
@jmccann Thanks for reporting this issue. I assume a lot of users will face the same issue. As far as I can see this, this is nothing we can fix in `kitchen-inspec`. I opened a ticket last week in `kitchen-docker` https://github.com/portertech/kitchen-docker/issues/193

cc @coderanger

**Comment by bigbam505** [comment] 2016-05-18 15:45
I think I might have duplicated the overall issue in #83 but I believe this is from a different reason.  Currently I can run inspec on a docker container directly but if I try and run it via the kitchen-inspec it will fail because of the following issue.  Not sure if the root cause is still an issue with the legacy driver or not.  Not sure if it makes more sense to just check for docker in the driver and if so set the inspec target to be the container_id which I believe uses docker exec instead of ssh.  Believe this is what happens with Dokken?

I believe just hooking into here could solve that easily https://github.com/chef/kitchen-inspec/blob/master/lib/kitchen/verifier/inspec.rb#L115-L133

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #verify action: [Sudo failed: Sudo requires a TTY. Please see the README on how to configure sudo to allow for non-interactive usage.]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by chris-rock** [comment] 2016-05-25 20:29
@jmccann I close this issue, since this was fixed in test-kitchen. If this is still an issue, please reopen the ticket.

**Closed by chris-rock** 2016-05-25 20:29 UTC
Labels: question

**Comment by jmccann** [comment] 2016-05-26 01:51
@chris-rock Yea, sorry ... should have responded ... it's been working for me! 💃
