### ISSUE TITLE
lost support for spec_helper in inspec

### ISSUE THREAD

**Issue by epcim** [chef/kitchen-inspec#93] opened 2016-07-07 12:13 UTC
The kitchen-inspec lost support to load helper files. See #249 or PR#12 (https://github.com/chef/kitchen-inspec/pull/12)

**Comment by epcim** [comment] 2016-07-07 12:20
kitchen-inspec is 0.14.x as of now, you probably suggesting downgrade inspec to v0.24.0 right?

**Comment by chris-rock** [comment] 2016-07-07 12:22
@epcim Yes this problem is located in inspec, once you downgrade to inspec 0.24.0 it should work as expected

**Comment by chris-rock** [comment] 2016-07-07 13:22
The issue is tracked at https://github.com/chef/inspec/pull/818

**Comment by adamleff** [comment] 2017-09-20 20:32
Since this issue is tracked already in the core InSpec project, I'm closing this issue.

**Closed by adamleff** 2017-09-20 20:32 UTC
