### ISSUE TITLE
Inspec Test Location

### ISSUE THREAD

**Issue by rneu31** [chef/kitchen-inspec#124] opened 2017-01-13 16:43 UTC
Is the default search location of kitchen-inspec going to be updated to match the standards direction that Chef is going in? Specifically discussed in chef/chef-dk#1096.

Additionally, gathered from reading discussions on issues, and reading the source https://github.com/chef/kitchen-inspec/blob/master/lib/kitchen/verifier/inspec.rb#L121, it seems as if `test/integration/suite_name` is the only intended supported location. 

The cookbook generator in the chef-dk creates `/test/recipes` so we have been storing our tests in `/test/recipes/suite_name` and kitchen-inspec finds them without having to explicitly point to them in kitchen.yml. https://github.com/chef/chef-dk/blob/627ff580d26c7452285de3d6c4f0692a762953f0/lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb#L58

What's the intended location, which one of these things is the "future", and how can I help align these things so they make sense for the next person learning Chef?

Just to keep these all linked: chef/chef-vault-testfixtures#24

**Comment by rmoriz** [comment] 2017-04-18 18:23
Chefdk's generator now creates `test/smoke/default/<recipe-name>.rb` … so is a now a mess :(

**Comment by chris-rock** [comment] 2017-04-18 19:23
Essentially, we have two paths built-in:
- `/test/integration`
- `/test/recipes`

`/test/integration` is the path that is the default path by test kitchen. Nothing changed here. `/test/recipes` was the first iteration to align the test directory to Chef wording. This is deprecated now and replaced with the latest iteration:  `test/smoke/default/<recipe-name>.rb`. 

Although it seems more complicated, things are actually more explicit. We are moving away for having implicit path locations like `test/integration` to explicit locations in `.kitchen.yml`.

- `/test/integration` keeps the default for non-chef users
 - `test/smoke/default/<recipe-name>.rb` is the default for chef cookbooks with definition in `.kitchen.yml`
- `/test/recipes` is deprecated and should not be used anymore

I hope that clears the air?

**Comment by rmoriz** [comment] 2017-04-18 19:39
I'm fine with every path, just make it consistent over all tools ASAP (chefdk's cookbook generator for example) so that I don't have to hardcode paths in my `.kitchen.yml`. Thanks ;-)

**Comment by chris-rock** [comment] 2017-04-18 19:40
ChefDK is generating the right `.kitchen.yml`. Therefore I am not sure what is missing.

**Comment by rmoriz** [comment] 2017-04-18 19:45
My problem was that I already had an existing cookbook and just tried the generator to create a new recipe (+ inspec test)...

I remember renaming some suites in the past and all the (then used) serverspecs were never executed anymore, so I get the point of beeing explicit.

**Comment by kpersohn** [comment] 2017-04-27 17:35
Our team likes to use the generator as a source of truth for where to structure tests for new development,  but we were reluctant to switch to `test/smoke/<suite>/<recipe>.rb` since Kitchen doesn't look there by default. I'm sympathetic to moving towards being more explicit since that would have avoided a lot of confusion in the first place; however, it still seems like a regression to go from providing convenience magic for the default location to dropping support for that. If you're a newbie following guides/documentation out on the web on the old behavior but using an updated path it can be a real head scratcher trying to figure out why your tests aren't running. 

One other data point worth mentioning is that [chef-vault-testfixtures](https://github.com/chef/chef-vault-testfixtures) only seems to look in `test/integration` for stubbed data bags. If `test/smoke` is the way of the future then it would be nice if that tool looked there so we don't need to keep `test/integration` around just for that use case.

**Comment by adamleff** [comment] 2017-09-20 20:20
I'm closing this issue for now as it does not appear there is anything actionable to do for `kitchen-inspec`. If I'm wrong about this, please let me know. Thank you!

**Closed by adamleff** 2017-09-20 20:20 UTC
